### ISSUE TITLE
Easier food settings for new players

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/OneLife#103]
Cherry-pick upstream changes:
> New food settings to ease new players into the difficulty of the game. New players get an extra eating bonus and a slower food decrement time.  These bonuses have a half life of 10 hours of playtime. Does not affect tutorial players, who still get the same "hard" food timing that the tutorial was designed for.

Relevant commits:
https://github.com/jasonrohrer/OneLife/commit/155d49e5ea6b273a8159872d8c7f1cee1535c57c
https://github.com/jasonrohrer/OneLife/commit/e99fe714d1b4a1c0cadd4a1a08098a7d51b9f592

As well as adjust the bonus half life to 25 hours of playtime (server/settings/newPlayerFoodBonusHalfLifeSeconds.ini -> 90000)

**Comment by TanyaPegasus** [comment]
Implemented by Risvh May 23 https://github.com/twohoursonelife/OneLife/commit/50264c895df1909ea2dc91dc5411415353c1c5fc
