### ISSUE TITLE
Client reports Infertile tag to photo server as a part of character name

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/OneLife#109]
It's my understanding that when the infertile tag was implemented, it was done so as an extension of the character name.
Would it be difficult for this to be reworked so that when other functions are referencing the character name, they don't incidentally pick up the infertile tag?
Or would these cases be limited enough that we can just make a workaround for submitting the photo?

https://github.com/twohoursonelife/OneLife/blob/c8a6ec9d363f30bdc5ef363db505882f7a8817a6/gameSource/LivingLifePage.cpp#L7679-L7684

@risvh ?

**Comment by risvh** [comment]
https://github.com/twohoursonelife/OneLife/pull/110

**Comment by connorhsm** [comment]
Resolved by #110
