### ISSUE TITLE
Reduce memory used by the OneLife server

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/OneLife#151]
This is a call for assistance.

We're fast approaching the need to upgrade our server again due to reaching its memory limits.

Typically, the OneLife server is a lot more CPU heavy than memory, but over time we have always observed the memory usage trending upwards.

Because of this upwards trend we have pinned the problem to relate to the age of the server map and how much has been explored, but I do not believe this has been proven. We have also in the past maintained maps for 6-12 months (average 10 players) this map is all but 1 month old and has experienced a significant boom in players (now averaging 60).

Today we restarted the game server process, which released some memory, but not much.
Two week view:
![image](https://user-images.githubusercontent.com/20902771/172049896-c1b09683-d4db-46f7-9d37-ff365c586616.png)

More than happy to provide further information or data to assist, greatly appreciate anyone who can help to diagnose any issues that may exist in the server or provide improvements for memory usage.

**Comment by IsGris** [comment]
If you're still bothered by this problem, I'd like to try to help, but it's not easy to look at all the files of the project that could potentially load memory, so if you provided a server memory dump and pdb file of compiled program to debug it. I would try to optimize the places that load memory

**Comment by connorhsm** [comment]
Thanks @IsGris , this problem is not of large concern, I don't quite recall why this hasn't reared it's head again. I'm guessing it was mitigated by some changes to the local database format.

We do however have an issue with CPU reporting as 100%, jump into #game-modding on Discord and I can point you to it if you're interested.
