### ISSUE TITLE
Merge fix for commands clashing with item guide search commands

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/OneLife#154]
Cherry pick this commit from upstream
https://github.com/jasonrohrer/OneLife/commit/de536031c4cb979e28d523a1817d444869dc12ef

This is required as searching for /diesel engine will be interrupted as /die and kill the player, also affecting /saddle as /sad emote.

Will require manual merge as we do not have features such as
- familyCommand
- leaderCommand
- followerCommand
- allyCommand
- unfollowCommand

**Comment by Riik** [comment]
I will try to pick this one up! Will need some time to get familiar with the build tools and get up and running, but hopefully I can make some progress in the next few weeks and open a PR

**Comment by Riik** [comment]
I've created a pull request to fix this issue: https://github.com/twohoursonelife/OneLife/pull/191
