### ISSUE TITLE
Document function and flow of updated title page

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/OneLife#159]
Refers to changes made in #156 

Required before passing build to beta testers.

**Comment by connorhsm** [comment]
### Overview
The menu screens have had a considerable design overhaul. The login page has been reworked into a two stage process. One part is for logging in and the other for specifying how you will spawn. After your first successful login and given you have completed the tutorial, you will always be presented the secondary screen, unless you press the back button to edit your login information.

This will also detail all new features and changes of the related PR.

**Family spawning:** Enter the name of the family you want to spawn into. Introduced to reduce SID spam. (Need to clarify effects if no family found, no fertiles etc)

**Seeds:** Seeds or Spawn Seeds have been renamed to Spawn Code for clarity. We encourage all experienced players to actively change their language to avoid confusion and help with a quick transition.

**Tool tips:** Most buttons now have relevant tool tips.

**New field locking UI:** When clicking outside a lockable field, the field will lock, hiding the data and displaying grey with lighter grey slanted lines. To unlock the field, you must click it and then click the yellow exclamation box to the right of the field. The three lockable fields are currently for username, key, and spawn code.

**New "pause" screen:** "Pausing" in the middle of the game using ESC will now display a redesigned "pause" screen. From here you can use ESC again to resume or in the bottom right you can use the menu to resume, access settings or quit.

**Twinning:** The player to initiate a friends lobby will dictate the way all friends spawn. Affected by tutorial completion (Joint tutorial) and spawn options (Normal, spawn code or family).

**Fertile age:** Has been increased from 14 to 15. Avoiding sudden baby births when Eve spawns at 14.

### Testing
*For beta testers*
Issues we would like reported during testing;
- Any crashes (Please follow crash reporting guide)
- Any unexpected, weird or unintuitive behaviour or issues you experience that you believe to be related or caused by any other items we've requested to be tested.

What needs testing:
- Family spawning
- Spawn code spawning
- Tutorial spawning
- All of the above as twins (Only the first twin should effect any settings)
- Field locking
- Pause menu
- Fertile age
- All UI consistency

### Images
First load
![image](https://user-images.githubusercontent.com/20902771/178201229-c8845cf9-786d-424b-ba38-1d4ca936316e.png)

Loading after tutorial complete
![image](https://user-images.githubusercontent.com/20902771/178201386-efd0528c-c27b-4270-b978-8977c2602c8b.png)

Primary page (Tutorial complete)
![image](https://user-images.githubusercontent.com/20902771/178201531-4dfddc87-c1d4-4710-ba22-1a421d57826a.png)

New field lock
![image](https://user-images.githubusercontent.com/20902771/178201585-9e6be156-0727-457a-aeb5-925dd84ead10.png)

New settings page
![image](https://user-images.githubusercontent.com/20902771/178201646-d5b44164-3e38-4d92-a036-8bfad6895e67.png)

Secondary page, twinning and spawning at a specific family
![image](https://user-images.githubusercontent.com/20902771/178201746-3a3542c3-d306-4346-8c30-c7616d1dd2fd.png)

Death page
![image](https://user-images.githubusercontent.com/20902771/178201831-5030be87-ee13-4b79-a98e-a7ffab79f09a.png)

Rebirth page
![image](https://user-images.githubusercontent.com/20902771/178201890-88aae52c-03f0-4ce4-9a35-0b5a86ad6e96.png)

Pause menu
![image](https://user-images.githubusercontent.com/20902771/178202015-fe13eed4-b103-4f04-a4e1-1e99abc0ece4.png)

@risvh Can you please briefly review for anything missed or conditions overlooked?

**Comment by risvh** [comment]
Worth mentioning that the family spawning is primarily a response to the suggestion (e.g. suggestion#661): if a spawn code is used and a family is alive near the spawn point, then be born as a baby in the family. Make more sense this way for the Eve than sharing the spawn code to randoms who wanna be born back in the family.
Noticed from the first pic that the PLAY button got the tips and text mixed up, see #162, which also brings back the custom server fields in setting page. You may wanna update the pics

**Comment by connorhsm** [comment]
These features have since been released.
