### ISSUE TITLE
Specifying seed in login box is confusing

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/OneLife#180]
With recent changes to the UI, login details are not frequently checked or seen.
If a user still has a seed specified in the login page, it will override a seed or family name specified in the spawn page, which leads to a poor user experience troubleshooting the issue.

The legacy ability to specify a seed in the username field on the login page should be removed.

**Comment by risvh** [comment]
Fixed with https://github.com/twohoursonelife/OneLife/commit/296f03b90bb5a4d4fdd5e62d7f8758cf0c295d88

**Comment by risvh** [comment]
Fixed with https://github.com/twohoursonelife/OneLife/commit/296f03b90bb5a4d4fdd5e62d7f8758cf0c295d88
