### ISSUE TITLE
Add Discord rich presence "Playing Two Hours One Life"

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/OneLife#186]
https://discord.com/rich-presence

https://discord.com/developers/docs/game-sdk/sdk-starter-guide

The rich presence may display the user's current in game family name and potentially whether they are fertile or not, allowing. This exposes limited information which would not directly identify who the player is in game, but it could be inferred depending on family population. 

Users have the ability to disable discord rich presence in their Discord settings if this is not preferred. I would prefer to implement as described and gather feedback.

**Comment by LittleTofoo** [comment]
Literally just dug up my login details to say I love this. I have manually forced my discord to say when I'm playing 2HOL because I like displaying my activity, but adding those details would be really cool :)
