### ISSUE TITLE
Add ability to query server list of alive players names, age and gender

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/OneLife#202]
An external application should have the ability to open a socket with the server to query a list of the current alive players names, age and gender.

This functionality could be used by external services such as our Discord bot [Dictator](https://github.com/twohoursonelife/dictator/) or [OneLifeWeb](https://github.com/twohoursonelife/OneLifeWeb) to create a display of current living players.

Dictator and OneLifeWeb is already able to achieve a similar goal by querying the server for a player count. Seen [here](https://github.com/twohoursonelife/dictator/blob/ae4b9c13f2a841539585c823d5f39a0cb736fd37/dictator/cogs/stats.py#L51) and [here](https://github.com/twohoursonelife/OneLifeWeb/blob/e9b91a5c29671310187b50a63a11d47f93d69e87/web/public/reflector/server.php#L162).

**Comment by Eboubaker** [comment]
will it be public or does it require some kind of basic authentication(token...) and which type?

**Comment by connorhsm** [comment]
Public, no authentication is fine.
