### ISSUE TITLE
Player death notifications sometimes display to everyone on the server instead of only those nearby

### ISSUE THREAD

**Issue by TanyaPegasus** [twohoursonelife/OneLife#209]
This is visible to those using the Hetuw mod, but we are unsure whether this is a Hetuw issue or server side. 

People have periodically reported that they saw a player death notification when they should have been alone in the area. It is not uncommon for someone to mention this in Phex chat and for several people to reply and say that they also saw it. 

May be related to player death age. 

Some players have also reported seeing multiple notifications (ie for all three triplets), but I don't have a source for this. 

**Examples:**
Jessie, Freddy and I were triplets and died of old age at 120. We were in Iri’s town and Mae saw the notification for Noodle Irie (me) in the BN capital. The towns are very far apart.

A player reported seeing a notification for Fernando Bull from their town. Again this was Jessie and I playing as triplets with another player. The other two triplets died at 120, however I died of starvation slightly earlier. 

_Above examples confirmed as far away and notification seen by multiple people. Below examples not confirmed:_

Eve Blaze:
http://play.twohoursonelife.com/lineageServer/server.php?action=character_page&id=895252
For this one, not a twin/triplet etc. did live to 120.

https://discord.com/channels/423293333864054833/609135467664900269/1121060168269058048 unnamed player died at 115

**Comment by connorhsm** [comment]
No recent reports
