### ISSUE TITLE
OneLife server file missing

### ISSUE THREAD

**Issue by AlifJian** [twohoursonelife/OneLife#239]
I run script to build server in server/installYourOwnServer but i didnt get OneLifeServer file to run server

**Comment by risvh** [comment]
Those scripts are leftover from OHOL. Use this instead https://github.com/risvh/miniOneLifeCompile

**Comment by AlifJian** [comment]
> Those scripts are leftover from OHOL. Use this instead https://github.com/risvh/miniOneLifeCompile

I try it in Ubuntu 24.04 , in output dir not have any of OneLiefeServer just clearCache.bat  debug.bat  wsl.bat

**Comment by risvh** [comment]
Did you follow the steps in https://github.com/risvh/miniOneLifeCompile/blob/main/README.md ?
And if you have a discord account, it would be easier to help you in our discord server https://discord.gg/DcTEcGkC
